### ISSUE TITLE
CH-13- Utworzyć numerację pól szachownicy WPF

### ISSUE THREAD

**Issue by karolinaJot** [mfurmanit/ChessWPF#13]
Numeracja (od 1-8 oraz od a-h) na zewnątrz szachownicy, liczby po lewej stronie, litery na dole – zgodnie z załączonym obrazem

![image](https://user-images.githubusercontent.com/43984219/69752071-bb8f2d80-1150-11ea-9e05-e9f16cea1da4.png)

**Comment by mfurmanit** [comment]
Na etapie projektu ustalono, że nie wykonujemy tego zadania. Plansza wygląda lepiej bez numeracji i nie jest ona potrzebna. :)
