### ISSUE TITLE
CH-16 - Stworzyć testy jednostkowe dla ruchu Wieżą

### ISSUE THREAD

**Issue by karolinaJot** [mfurmanit/ChessWPF#16]
Stworzyć testy i przetestować poprawność logiki ruchu Wieżą oraz poprawność wyświetlania ruchu na planszy.

**Comment by michalWSEI** [comment]
Mam przypisany task w dokumencie na naszym dysku Google:
https://docs.google.com/document/d/16KcWh0GZE9pbfyZ9cxG4fz1pYbzrCgU9xfho1pePS_o/edit?usp=sharing

Dlatego chciałem przypisać do siebie ten Issius, nie wiem czemu nie mogę siebie przpisać z poziomu konta `michalWSEI`

**Comment by michalWSEI** [comment]
Mam taka samą sytuację z przypisywaniem labelów, nawet do Issus które stworzyłem z konta `michalWSEI`

**Comment by mfurmanit** [comment]
1. FiguresBasicMovesTests - testy dla podstawowych ruchów wszystkich figur na planszy.
2. FiguresAdvancedMovesTests - testy "zaawansowane" z przechodzeniem figur po planszy i zbijaniem.
3. FiguresInitializationTests - testy sprawdzające, czy figury i kafelki na planszy zostały zainicjalizowane poprawnie.
![image](https://user-images.githubusercontent.com/48626088/71828693-1fd3d400-30a3-11ea-887d-a50734f5b257.png)
