### ISSUE TITLE
CH-19 - Stworzyć testy jednostkowe dla ruchu Pionkiem

### ISSUE THREAD

**Issue by karolinaJot** [mfurmanit/ChessWPF#19]
Stworzyć testy i przetestować poprawność logiki ruchu Pionkiem oraz poprawność wyświetlania ruchu na planszy.

**Comment by mfurmanit** [comment]
1. FiguresBasicMovesTests - testy dla podstawowych ruchów wszystkich figur na planszy.
2. FiguresAdvancedMovesTests - testy "zaawansowane" z przechodzeniem figur po planszy i zbijaniem.
3. FiguresInitializationTests - testy sprawdzające, czy figury i kafelki na planszy zostały zainicjalizowane poprawnie.
![image](https://user-images.githubusercontent.com/48626088/71828693-1fd3d400-30a3-11ea-887d-a50734f5b257.png)
