### ISSUE TITLE
CH-2 - Utworzyć białe kafelki na planszy.

### ISSUE THREAD

**Issue by mfurmanit** [mfurmanit/ChessWPF#2]
Należy utworzyć białe kafelki na planszy - WPF.

**Comment by karolinaJot** [comment]
Proponuję, żeby zamiast czarnych i białych kafelków zrobić inny wariant kolorystyczny. Chodzi o to, żeby nie było problemu z wyświetlaniem czarnych figur na czarnym polu. Z białymi figurami nie ma takiego problemu, bo wszystkie, które znalazłam mają czarny obrys :P 
Poniżej zdjęcie planszy z bardzo ładnym zestawem kolorystycznym

![przykladPlanszy](https://user-images.githubusercontent.com/43984219/69992321-b0217500-1549-11ea-86a7-194e3fa14170.png)

**Comment by mfurmanit** [comment]
Gotowe.
