### ISSUE TITLE
CH-20- Inicjowanie ruchu figury po szachownicy - implementacja części wizualnej

### ISSUE THREAD

**Issue by karolinaJot** [mfurmanit/ChessWPF#20]
Wybranie figury, która ma wykonać ruch - Gracz wybiera figurę, którą chce wykonać ruch – klika na tę figurę (na pole na którym aktualnie znajduje się figura) – pole na którym znajduje się figura dostaje zielone obramowanie.

**Comment by mfurmanit** [comment]
@karolinaJot 
Niebieskie obramowanie - aktualnie wybrana figura.
Zielone obramowanie - miejsce, na które pionek może się przemieścić.
Czerwone obramowanie - miejsca, na które pionek NIE może się przemieścić.
