### ISSUE TITLE
CH-21- Ruch po szachownicy - implementacja przesunięcia figury (część wizualna)

### ISSUE THREAD

**Issue by karolinaJot** [mfurmanit/ChessWPF#21]
Gracz wybiera pole, na które chce przesunąć wybraną figurę, poprzez kliknięcie w odpowiedni kwadrat. 
Ruch prawidłowy: figura „przesuwa” się na wskazane, dozwolone, pole – znika z pola dotychczasowego i pojawia się na nowym polu.

Ruch nieprawidłowy: figura nie zmienia swoje położenia, czeka na ruch prawidłowy. Jeśli gracz wskaże pole, na które wybrana figura nie może wykonać ruchu, to po kliknięciu przez gracza w to niedozwolone pole, na tym polu pojawi się czerwone obramowanie – jako sygnał, że ta figura nie może wykonać ruchu na to pole.

Jeśli ruch został wykonany znikają obramowania poszczególnych pól, licznik czasu gracza zeruje się.  Teraz jest kolej drugiego gracza, licznik czasu staruje (odlicza od 30 sekund do 0).

**Comment by mfurmanit** [comment]
@karolinaJot 
Niebieskie obramowanie - aktualnie wybrana figura (jest cały czas jeśli figura jest wybrana.
Zielone obramowanie - miejsce, na które pionek może się przemieścić (pojawia się po najechaniu na pole).
Czerwone obramowanie - miejsca, na które pionek NIE może się przemieścić (pojawia się po najechaniu na pole).

Zostało obsłużenie przypadku kiedy następuje kolej drugiego gracza (zdjęcie wszystkich borderów).
