### ISSUE TITLE
CH-23- Panel boczny - implementacja przycisku "cofnij ruch"

### ISSUE THREAD

**Issue by karolinaJot** [mfurmanit/ChessWPF#23]
Jeden przycisk, wspólny dla obu graczy. Gracz, który właśnie wykonał ruch, dopóki jego czas się nie zatrzymał, ma możliwość cofnięcia tego ruchu i wykonania nowego.  W przypadku skorzystania z gracza z opcji "Cofnij ruch"  czas się nie zatrzymuje. Gracz po wykonaniu swojego ruchu musi kliknąć w swój zegar żeby go zatrzymać - to kliknięcie automatycznie uruchamia zegar przeciwnika.

**Comment by mfurmanit** [comment]
To na koniec jak zostanie czas.

**Comment by mfurmanit** [comment]
Nie realizujemy funkcjonalności cofania ruchu. :)
