### ISSUE TITLE
CH-25 ruchu zbijający dla pionka

### ISSUE THREAD

**Issue by michalWSEI** [mfurmanit/ChessWPF#25]
Utworzenie zakresu ruchu zbijającego dla pionka,

-- Stworzenie metody w obiekcie pionka, w której zostanie opisane co się stanie gdy zostanie wydany ruch mający na celu zbicie innej figury

**Comment by mfurmanit** [comment]
Ruch zbijający został zaimplementowany na etapie wykonywania ruchu pionkiem.
