### ISSUE TITLE
CH-26 ruchu zbijającego dla wieży

### ISSUE THREAD

**Issue by michalWSEI** [mfurmanit/ChessWPF#26]
Utworzenie zakresu ruchu zbijającego dla wierzy. 

Obiekt wieża => metoda zbicie wieża => określenie co się stanie gdy zostanie wydany ruch, który na drodze spotka figury drużyny przeciwnej

**Comment by mfurmanit** [comment]
Ruch zbijający został zaimplementowany na etapie wykonywania ruchu pionkiem.
