### ISSUE TITLE
CH - 27 Ruch zbijający dla gońca

### ISSUE THREAD

**Issue by michalWSEI** [mfurmanit/ChessWPF#27]
Utworzenie zakresu ruchu zbijającego dla gońca. 

Obiekt goniec => metoda zbicie gońcem => określenie co się stanie gdy zostanie wydany ruch, który na drodze spotka figury drużyny przeciwnej

**Comment by mfurmanit** [comment]
Ruch zbijający został zaimplementowany na etapie wykonywania ruchu pionkiem.
