### ISSUE TITLE
CH - 28 ruch zbijający dla królowej

### ISSUE THREAD

**Issue by michalWSEI** [mfurmanit/ChessWPF#28]
Utworzenie zakresu ruchu zbijającego dla królowej. 

Obiekt królowa => metoda zbicie przez królową => określenie co się stanie gdy zostanie wydany ruch, który na drodze spotka figury drużyny przeciwnej

**Comment by mfurmanit** [comment]
Ruch zbijający został zaimplementowany na etapie wykonywania ruchu pionkiem.
