### ISSUE TITLE
CH 29 - ruch zbijający dla Króla

### ISSUE THREAD

**Issue by michalWSEI** [mfurmanit/ChessWPF#29]
Utworzenie zakresu ruchu zbijającego dla króla. 

Obiekt króla => metoda zbicie przez króla => określenie co się stanie gdy zostanie wydany ruch, który na drodze spotka figury drużyny przeciwnej

**Comment by mfurmanit** [comment]
Ruch zbijający został zaimplementowany na etapie wykonywania ruchu pionkiem.
