### ISSUE TITLE
CH-3 - Utworzyć czarne kafelki na planszy.

### ISSUE THREAD

**Issue by mfurmanit** [mfurmanit/ChessWPF#3]
Należy utworzyć czarne kafelki na planszy - WPF.

**Comment by karolinaJot** [comment]
Proponuję, żeby zamiast czarnych i białych kafelków zrobić inny wariant kolorystyczny. Chodzi o to, żeby nie było problemu z wyświetlaniem czarnych figur na czarnym polu. Z białymi figurami nie ma takiego problemu, bo wszystkie, które znalazłam mają czarny obrys :P 
Poniżej zdjęcie planszy z bardzo ładnym zestawem kolorystycznym

![przykladPlanszy](https://user-images.githubusercontent.com/43984219/69992379-d34c2480-1549-11ea-9c5e-3b1aec5f4cee.png)

**Comment by mfurmanit** [comment]
Gotowe.
