### ISSUE TITLE
CH - 30 ruch zbijający dla skoczka

### ISSUE THREAD

**Issue by michalWSEI** [mfurmanit/ChessWPF#30]
Utworzenie zakresu ruchu zbijającego dla skoczka. 

Obiekt skoczka => metoda zbicie przez skoczka => określenie co się stanie gdy zostanie wydany ruch, który na drodze spotka figury drużyny przeciwnej

**Comment by mfurmanit** [comment]
Ruch zbijający został zaimplementowany na etapie wykonywania ruchu pionkiem.
