### ISSUE TITLE
CH 31 - utworzenie tablicy z łączną pulą dostępnych figur 

### ISSUE THREAD

**Issue by michalWSEI** [mfurmanit/ChessWPF#31]
Stworzenie tablicy asocjacyjnej, 
---- W której każdy element będzie odpowiedzialny za figurę dostępna dla poszczególnego gracza
---- dwie tablice, po jednej dla każdego z gracza
---- będzie ona opróżniana po ruchu zbijącym 
---- kazdy element o typu true/false, o indeksie np.: 'pionek'

**Comment by mfurmanit** [comment]
Zrealizowane mniej więcej poprzez property **possiblePositions**.
