### ISSUE TITLE
CH - 32 obsługa wyjątku, ruch nie dozwolony poza planszę

### ISSUE THREAD

**Issue by michalWSEI** [mfurmanit/ChessWPF#32]
--- stworzenie nowego typu wyjatku 'withoutRangBoard' albo cos w tym stylu nazwa do ustalenia ;)
--- określenie co sie stanie gdy uzytkownik będzie chciał określi ruch poza dozowlone przestrzen

**Comment by mfurmanit** [comment]
Użytkownik może klikać poza zakresem planszy w dowolny sposób - tak jak działa każde inne okno w Windows. Implementacja blokady ruchu na zakazane pola została już wykonana.
