### ISSUE TITLE
CH 33 Obsługa wyjątku ruch nie dozwolony, poza zakres dla danej figury

### ISSUE THREAD

**Issue by michalWSEI** [mfurmanit/ChessWPF#33]
--- stworzenie typu wyjatku
--- określenie co się stanie po tym wyjatku, może warning jakis, albo coś wzgeldnie prostego

**Comment by mfurmanit** [comment]
Implementacja blokady ruchu na zakazane pola została już wykonana - czerwone obramowanie + brak eventu.
