### ISSUE TITLE
CH - 36 - Zakończenie gry - przypadki zakończenia partii

### ISSUE THREAD

**Issue by karolinaJot** [mfurmanit/ChessWPF#36]
Dana partia kończy się gdy:
1. jednemu z graczy upłynie czas (czas osiągnie 00:00:00);
2. jest szach-mat;
3. jest remis;

**Comment by mfurmanit** [comment]
Na etapie realizacji projektu uznano, że zawodnicy sami będą decydować o zakończeniu partii w dowolnie wybranym przez nich momencie przy użyciu przycisku zakończ partię.

W przypadku, gdy upłynie limit czasu na ruch dla danego gracza kolejka przechodzi na przeciwnika i licznik jest resetowany.

@karolinaJot
