### ISSUE TITLE
CH-4 - Utworzyć część boczną z informacjami o rozgrywce.

### ISSUE THREAD

**Issue by mfurmanit** [mfurmanit/ChessWPF#4]
Należy utworzyć "część boczną" z informacjami o graczach, czasie rozgrywki i innymi wymaganymi komponentami.

**Comment by michalWSEI** [comment]
-- zmiany wprowadzam na branchu sidebar, który stworzyłem do tego zadania
-- można przemyśleć wprowadzenie features branch'u, np.: CH-4, do zastanowienia się

**Comment by michalWSEI** [comment]
siedzę nad XAML 'em .... i jest jeszcze sporo do zrobienia w tym tasku
--- jak narazie zrobiłem kontrolkę, po której kliknięciu, wyświetla się sidebar

**Comment by karolinaJot** [comment]
Zrobione
