### ISSUE TITLE
CH - 40 - Wybór koloru pionków i nazwy gracza po uruchomieniu aplikacji

### ISSUE THREAD

**Issue by mfurmanit** [mfurmanit/ChessWPF#43]
Po uruchomieniu aplikacji powinien wyświetlić się Dialog/MessageBox/Window z:
a) Dwoma TextBoxami do wpisania nazw jednego i drugiego gracza.
b) Dwoma polami składającymi się z dwóch Radio Button Group określających kolor pionków (białe/czarne). Kiedy zmieniamy kolor dla jednego z graczy, dla drugiego następuje to automatycznie.
c) Przycisk "Rozpocznij rozgrywkę"

**Comment by karolinaJot** [comment]
Zrobione
