### ISSUE TITLE
CH-43 dodanie roszady (uczestniczą Król i Wieża)

### ISSUE THREAD

**Issue by karolinaJot** [mfurmanit/ChessWPF#49]
Roszada – specyficzny ruch w szachach, w którym jednocześnie uczestniczą król i jedna z wież tego samego koloru. Roszada polega na przesunięciu króla o dwa pola w kierunku wieży, a następnie ustawieniu wieży na polu, które minął król. Diagramy obok ilustrują to posunięcie.

![roszada](https://user-images.githubusercontent.com/43984219/71327209-f6914080-2505-11ea-8aeb-984d79506b47.png)

**Comment by mfurmanit** [comment]
Wykonane przez @karolinaJot
