### ISSUE TITLE
CH-44 Zmiana języka z polskiego na angielski w interfejsie użytkownika 

### ISSUE THREAD

**Issue by karolinaJot** [mfurmanit/ChessWPF#50]

**Comment by mfurmanit** [comment]
![image](https://user-images.githubusercontent.com/48626088/71778636-9fcd4180-2fb0-11ea-9ac8-695b7377f2ed.png)
![image](https://user-images.githubusercontent.com/48626088/71778648-be333d00-2fb0-11ea-8977-f5ff605e2202.png)
![image](https://user-images.githubusercontent.com/48626088/71778650-c68b7800-2fb0-11ea-86e5-ebc1151ec79b.png)
![image](https://user-images.githubusercontent.com/48626088/71778674-02bed880-2fb1-11ea-8637-e630813691e6.png)

Gotowe.
